POST http://localhost:5000/api/auth/register
Content-type: application/json

{
    "username":"NguyenAnh",
    "password":"Bang2269@"
}

###

POST http://localhost:5000/api/auth/login
Content-type: application/json

{
    "username":"NguyenAnh",
    "password":"Bang2269@"
}
###
POST http://localhost:5000/api/post
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjcwMDIzMWYwYmE4NTc1YWZiZmZjZTIiLCJpYXQiOjE2NTE1MDc3OTB9.F7kNjj29aVU8kiUtGKYPfAYtTK_XTvmLGNAjtarGxXE

{
 "title": "Pay bills, clean the house",
    "status": true,
    "description":"Regain clarity and calmness by getting all those tasks out of your head and onto your to-do list (no matter where you are or what device you use).",
    "createDate":"16/12/2022"
}
###
GET http://localhost:5000/api/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjZlMzZjNzIyZTI0MGNhNThhYTEyY2MiLCJpYXQiOjE2NTEzOTA3MDh9.ECd0apEIu3sEsgKemChErDhvPI2rrheR2L09SkGiDWU

###
PUT http://localhost:5000/api/post/626e377eff94d729f02b0d78
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjZlMzZjNzIyZTI0MGNhNThhYTEyY2MiLCJpYXQiOjE2NTEzOTA3MDh9.ECd0apEIu3sEsgKemChErDhvPI2rrheR2L09SkGiDWU


{
 "title": "Do my homework on Thursday",
    "status": false,
    "description":"Math, english...",
    "createDate":"13/12/2022"
}
###
DELETE http://localhost:5000/api/post/626e3cce21f65ad03cf2bf97
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjZlMzZjNzIyZTI0MGNhNThhYTEyY2MiLCJpYXQiOjE2NTEzOTA3MDh9.ECd0apEIu3sEsgKemChErDhvPI2rrheR2L09SkGiDWU

